import SideNav from "./components/SideNav";
import "./styles/globals.css";
import { Inter } from "next/font/google";

import getCurrentUser from "app/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  console.log("🚀 ~ SideNav ~ currentUser:", currentUser);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto flex items-start sm:pr-4">
          <SideNav currentUser={currentUser} />
          <div className="min-h-screen flex-grow border-x">{children}</div>
        </div>
      </body>
    </html>
  );
}
